### ISSUE TITLE
Insert term relations in termentry template topic

### ISSUE THREAD

**Issue by SanFanDocu** [doctales/org.doctales.terminology#1]
Authoring a new term entry will be much easier in oxygen author mode when term relation structure is predefined within the template.

**Comment by xephon2** [comment]
The relation structure is already defined. This screencast demonstrates, how to insert a term relation in author mode:

![addtermrelation](https://cloud.githubusercontent.com/assets/3266567/18487079/2048e01a-79f4-11e6-8130-e72890f2f988.gif)

**Comment by SanFanDocu** [comment]
ah ok, was irritated because most other elements are preset within the template. If I know that all elements can be inserted via the "Term Administration" line that´s ok.
I knew the position where the 'relations' element must be inserted and have been looking there first for a "add button".
