### ISSUE TITLE
Oxygen does not load termmap doctype association from frameworks folder

### ISSUE THREAD

**Issue by SanFanDocu** [doctales/org.doctales.terminology#22]
If  I set the associated framework location to `org.doctales.terminology/framework/`
Oxygen (18.1 + 19) finds the `termentry` doctype association only but not the `termmap` doctype association.
Because of that, Oxygen does not provide the author with any transformation scenario.

It seems that Oxygen ecxpects that multiple frameworks must located in separate subdirecories of the added framework directory. 
If I try to safe a new external framework in the top level frameworks dirctory the following message occours:
>The "*.framework" file must be saved in a subdirectory of one of the configured frameworks directories..."

Moving the framework and referenced ressources in a subdirectory solves the problem. 
Associated ransformation scenarios are available after that.
However, I facing another transformation failure 
`java.lang.ClassNotFoundException: org.dita.dost.module.GenMapAndTopicListModule`,
 so I am not shure, if other things are to do regarding this issue.

**Comment by xephon2** [comment]
You just have to add the plugin directory itself as a framework directory in oXygen, e.g. `~/dita-ot/plugins/org.doctales.terminology`

**Comment by xephon2** [comment]
```bash
java.lang.ClassNotFoundException: org.dita.dost.module.GenMapAndTopicListModule
``` 
@SanFanDocu, this error means, that the DITA-OT cannot run, because the `dost.jar` library is not found, which contains the `GenMapAndTopicListModule` Java class. This is the first Java library, that is loaded when launching the toolkit. Usually this means, that the classpath is messed up. Which transformation did you call? Did you call the transformation by clicking on the oXygen Ant transformation scenario?

**Comment by SanFanDocu** [comment]
> Did you call the transformation by clicking on the oXygen Ant transformation scenario?

Yes, like a novice would try :wink:. 
Had the problem with all doctales transtypes. 
After adding the dost.jar other failures occured depending on other missing .jars

My dirty (but working) solution is to add missing jars to the liberary and set all entries to absolute paths. 
`The classpath is messed up` for me :sweat: !

**Comment by xephon2** [comment]
I thought classpaths are easies to handle with Ant-based transformations. I was wrong. I added a new transformation (additional, temporarily) for the termbrowser responsive, which is a normal DITA-OT transformation scenario. This should now work for you without any errors. If yes, please close this issue.
