### ISSUE TITLE
add support for alternative definitions

### ISSUE THREAD

**Issue by lionelmoi** [doctales/org.doctales.terminology#25]
A single term may have different definitions, that is, not different meanings but different angles (customer, terminologist, student, manager, SME).

It would be interesting to add a `<definitionAlt>` element based on `topic/section` in the termBody in order to implement it.

**Comment by xephon2** [comment]
@lionelmoi, could you please use the `develop` branch and test, whether you are happy with the new `<altDefinition>` element?

**Comment by lionelmoi** [comment]
Really sorry I did not answer. Lots to do and so little time.

Yes this solution works for me.
