### ISSUE TITLE
Please add support for HiDPI displays

### ISSUE THREAD

**Issue by Schelmenzunft** [doctales/org.doctales.terminology#27]
On a 4K display the termbrowser displays text that's too tiny to read, in some cases the letters overlap. Would be nice to use this on my new 32" display :-). Thx.

**Comment by xephon2** [comment]
@SanFanDocu, I'll check the stylesheets. I think @Schelmenzunft means the **author view** of the `termentry` topic (and not the termbrowser). Could you than please check the result on your HiDPI screen?

**Comment by xephon2** [comment]
@SanFanDocu, could you please check the `develop` branch on your HiDPI screen using the dark Graphite theme?

**Comment by xephon2** [comment]
@Schelmenzunft Could you please check the `develop` branch?

**Comment by xephon2** [comment]
Fixed by simplifying the font chain.
