### ISSUE TITLE
Make plugins works with DITA OT 3.6

### ISSUE THREAD

**Issue by raducoravu** [doctales/org.doctales.terminology#36]
We had this remark from one of our users:

     We have looked at Doctales’ terminology plugin (https://github.com/doctales/org.doctales.terminology). 
     This has great functionality as it offers not only the possibility to check for incorrect terms, but also to manage terms and concepts like in a terminology database. 
     However, this plugin is seemingly not maintained any more and does not work with DITA-OT 3.6.

**Comment by xephon2** [comment]
@raducoravu, I'll look into this, but currently I need all my time to get our XSL:FO PDF processing running. If the environment is working properly, I'll have the time to investigate and fix this.

**Comment by raducoravu** [comment]
The fatal error I get with DITA OT 3.6 is this:

     BUILD FAILED
    /.../DITA-OT3.x/plugins/org.dita.base/build.xml:29: The following error occurred while executing this line:
    /..../DITA-OT3.x/plugins/org.doctales.terminology-master/build_dita2termchecker-dita_template.xml:29: 
    Includesfile ..../DITA-OT3.x/plugins/org.doctales.terminology-master/samples/temp/termchecker-dita/${fullditatopicfile} not found.
